models:
  - name: stg_tpch__part_suppliers
    columns:
      - name: part_supplier_sk
        description: "{{ doc('part_supplier_sk') }}"
        tests:
          - unique
          - not_null
      - name: part_supplier_available_qty
        tests:
          - not_null:
              config:
                severity: error
                error_if: ">80"
                warn_if: ">0"
                where: "part_supplier_cost > 0"
